spring:
  #  DB Configuration.
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_auth
    username: postgres
    password: root

  #  Hibernate Config.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Security Config.
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # A Day
      refresh-token:
        expiration: 604800000 # 7 Days
